allowBuilds:
  "@sentry/cli": true
  esbuild: true
  unrs-resolver: true
  workerd: true
engineStrict: true
overrides:
  "esbuild@<=0.24.2": 0.25.12
saveExact: true
strictDepBuilds: true
strictPeerDependencies: true
