-- Generated by drizzle-kit 0.31.10 after manual foreign-key coverage review.
CREATE INDEX "listing_daily_totals_last_ledger_idx" ON "app"."listing_daily_totals" USING btree ("last_ledger_entry_id");--> statement-breakpoint
CREATE INDEX "listings_logo_asset_idx" ON "app"."listings" USING btree ("logo_asset_id");--> statement-breakpoint
CREATE INDEX "admin_users_created_by_idx" ON "private"."admin_users" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "financial_ledger_reverses_idx" ON "private"."financial_ledger" USING btree ("reverses_ledger_entry_id");--> statement-breakpoint
CREATE INDEX "financial_ledger_created_admin_idx" ON "private"."financial_ledger" USING btree ("created_by_admin_user_id");--> statement-breakpoint
CREATE INDEX "listing_change_requests_requester_idx" ON "private"."listing_change_requests" USING btree ("requested_by_user_id");--> statement-breakpoint
CREATE INDEX "listing_change_requests_reviewer_idx" ON "private"."listing_change_requests" USING btree ("reviewed_by_admin_id");--> statement-breakpoint
CREATE INDEX "listing_owners_user_idx" ON "private"."listing_owners" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "listing_owners_created_by_idx" ON "private"."listing_owners" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "moderation_actions_admin_user_idx" ON "private"."moderation_actions" USING btree ("admin_user_id");--> statement-breakpoint
CREATE INDEX "operational_flags_updated_by_idx" ON "private"."operational_flags" USING btree ("updated_by");--> statement-breakpoint
CREATE INDEX "payment_attempts_target_listing_idx" ON "private"."payment_attempts" USING btree ("target_listing_id_snapshot");--> statement-breakpoint
CREATE INDEX "payment_attempts_pending_owner_idx" ON "private"."payment_attempts" USING btree ("pending_owner_id");--> statement-breakpoint
CREATE INDEX "pending_listing_owners_attempt_idx" ON "private"."pending_listing_owners" USING btree ("created_from_attempt_id");--> statement-breakpoint
CREATE INDEX "pending_listing_owners_claimed_user_idx" ON "private"."pending_listing_owners" USING btree ("claimed_by_user_id");--> statement-breakpoint
CREATE INDEX "provider_adjustments_listing_idx" ON "private"."provider_adjustments" USING btree ("listing_id");--> statement-breakpoint
CREATE INDEX "provider_adjustments_applies_ledger_idx" ON "private"."provider_adjustments" USING btree ("applies_to_ledger_entry_id");--> statement-breakpoint
CREATE INDEX "reconciliation_items_resolved_by_idx" ON "private"."reconciliation_items" USING btree ("resolved_by");--> statement-breakpoint
CREATE INDEX "reports_reviewer_idx" ON "private"."reports" USING btree ("reviewed_by_admin_id");
