-- Generated by drizzle-kit 0.31.10 from src/server/db/schema and promoted
-- into the authoritative Supabase migration workflow. Manually reviewed
-- Phase 2 platform-specific constraints, grants, seeds and protections follow.
CREATE SCHEMA "app";
--> statement-breakpoint
CREATE SCHEMA "private";
--> statement-breakpoint
CREATE TABLE "app"."categories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"sort_order" smallint NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "categories_slug_unique" UNIQUE("slug"),
	CONSTRAINT "categories_name_unique" UNIQUE("name"),
	CONSTRAINT "categories_sort_order_unique" UNIQUE("sort_order"),
	CONSTRAINT "categories_sort_order_positive" CHECK ("app"."categories"."sort_order" > 0),
	CONSTRAINT "categories_slug_canonical" CHECK ("app"."categories"."slug" ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);
--> statement-breakpoint
CREATE TABLE "app"."listing_assets" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"listing_id" uuid,
	"kind" text NOT NULL,
	"state" text NOT NULL,
	"staging_bucket" text,
	"staging_object_key" text,
	"public_bucket" text,
	"public_object_key" text,
	"content_type" text,
	"byte_size" bigint,
	"width" integer,
	"height" integer,
	"sha256" text,
	"rejection_code" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"processed_at" timestamp with time zone,
	"expires_at" timestamp with time zone,
	CONSTRAINT "listing_assets_kind_valid" CHECK ("app"."listing_assets"."kind" = 'logo'),
	CONSTRAINT "listing_assets_state_valid" CHECK ("app"."listing_assets"."state" in ('staged', 'processing', 'ready', 'rejected', 'orphaned')),
	CONSTRAINT "listing_assets_byte_size_nonnegative" CHECK ("app"."listing_assets"."byte_size" is null or "app"."listing_assets"."byte_size" >= 0),
	CONSTRAINT "listing_assets_dimensions_positive" CHECK (("app"."listing_assets"."width" is null or "app"."listing_assets"."width" > 0) and ("app"."listing_assets"."height" is null or "app"."listing_assets"."height" > 0))
);
--> statement-breakpoint
CREATE TABLE "app"."listing_click_daily_totals" (
	"listing_id" uuid NOT NULL,
	"business_date" date NOT NULL,
	"unique_clicks" bigint DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "listing_click_daily_totals_listing_id_business_date_pk" PRIMARY KEY("listing_id","business_date"),
	CONSTRAINT "listing_click_daily_totals_nonnegative" CHECK ("app"."listing_click_daily_totals"."unique_clicks" >= 0)
);
--> statement-breakpoint
CREATE TABLE "app"."listing_daily_totals" (
	"listing_id" uuid NOT NULL,
	"business_date" date NOT NULL,
	"net_amount_paise" bigint DEFAULT 0 NOT NULL,
	"total_reached_at" timestamp with time zone NOT NULL,
	"last_ledger_entry_id" uuid NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "listing_daily_totals_listing_id_business_date_pk" PRIMARY KEY("listing_id","business_date"),
	CONSTRAINT "listing_daily_totals_whole_rupees" CHECK ("app"."listing_daily_totals"."net_amount_paise" % 100 = 0)
);
--> statement-breakpoint
CREATE TABLE "app"."listings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"public_id" text NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"name_normalized" text NOT NULL,
	"tagline" text NOT NULL,
	"destination_url" text NOT NULL,
	"destination_canonical_key" text NOT NULL,
	"destination_host" text NOT NULL,
	"category_id" uuid NOT NULL,
	"logo_asset_id" uuid,
	"lifecycle_status" text NOT NULL,
	"moderation_status" text NOT NULL,
	"confirmed_total_paise" bigint DEFAULT 0 NOT NULL,
	"original_sponsorship_paise" bigint,
	"current_total_reached_at" timestamp with time zone,
	"first_confirmed_at" timestamp with time zone,
	"last_rank_change_at" timestamp with time zone,
	"category_locked_at" timestamp with time zone,
	"moderation_reason_code" text,
	"removed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version" bigint DEFAULT 1 NOT NULL,
	CONSTRAINT "listings_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "listings_slug_unique" UNIQUE("slug"),
	CONSTRAINT "listings_destination_canonical_key_unique" UNIQUE("destination_canonical_key"),
	CONSTRAINT "listings_lifecycle_status_valid" CHECK ("app"."listings"."lifecycle_status" in ('draft', 'payment_pending', 'active', 'inactive_reversed', 'removed')),
	CONSTRAINT "listings_moderation_status_valid" CHECK ("app"."listings"."moderation_status" in ('unreviewed', 'pending_review', 'clear', 'suspended')),
	CONSTRAINT "listings_total_nonnegative" CHECK ("app"."listings"."confirmed_total_paise" >= 0),
	CONSTRAINT "listings_total_whole_rupees" CHECK ("app"."listings"."confirmed_total_paise" % 100 = 0),
	CONSTRAINT "listings_original_valid" CHECK ("app"."listings"."original_sponsorship_paise" is null or ("app"."listings"."original_sponsorship_paise" >= 49900 and "app"."listings"."original_sponsorship_paise" % 100 = 0)),
	CONSTRAINT "listings_active_financial_state_valid" CHECK ("app"."listings"."lifecycle_status" <> 'active' or ("app"."listings"."original_sponsorship_paise" is not null and "app"."listings"."confirmed_total_paise" > 0)),
	CONSTRAINT "listings_inactive_reversed_state_valid" CHECK ("app"."listings"."lifecycle_status" <> 'inactive_reversed' or ("app"."listings"."original_sponsorship_paise" is not null and "app"."listings"."confirmed_total_paise" = 0)),
	CONSTRAINT "listings_unconfirmed_state_valid" CHECK ("app"."listings"."original_sponsorship_paise" is not null or ("app"."listings"."confirmed_total_paise" = 0 and "app"."listings"."current_total_reached_at" is null and "app"."listings"."first_confirmed_at" is null)),
	CONSTRAINT "listings_version_positive" CHECK ("app"."listings"."version" > 0),
	CONSTRAINT "listings_destination_https" CHECK ("app"."listings"."destination_url" ~ '^https://')
);
--> statement-breakpoint
CREATE TABLE "private"."admin_audit_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"actor_user_id" uuid NOT NULL,
	"actor_role" text NOT NULL,
	"action" text NOT NULL,
	"target_type" text NOT NULL,
	"target_id" text NOT NULL,
	"request_id" text NOT NULL,
	"reason" text,
	"before_snapshot" jsonb,
	"after_snapshot" jsonb,
	"ip_hmac" text,
	"user_agent_summary" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "admin_audit_events_request_action_target_unique" UNIQUE("request_id","action","target_type","target_id")
);
--> statement-breakpoint
CREATE TABLE "private"."admin_users" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"role" text NOT NULL,
	"is_active" boolean NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"revoked_at" timestamp with time zone,
	CONSTRAINT "admin_users_role_valid" CHECK ("private"."admin_users"."role" in ('reviewer', 'operations', 'super_admin'))
);
--> statement-breakpoint
CREATE TABLE "private"."click_dedupe" (
	"listing_id" uuid NOT NULL,
	"business_date" date NOT NULL,
	"visitor_hmac" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	CONSTRAINT "click_dedupe_listing_id_business_date_visitor_hmac_pk" PRIMARY KEY("listing_id","business_date","visitor_hmac"),
	CONSTRAINT "click_dedupe_expiry_after_creation" CHECK ("private"."click_dedupe"."expires_at" > "private"."click_dedupe"."created_at")
);
--> statement-breakpoint
CREATE TABLE "private"."email_outbox" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kind" text NOT NULL,
	"recipient_encrypted" text NOT NULL,
	"recipient_hash" text NOT NULL,
	"template_version" text NOT NULL,
	"payload" jsonb NOT NULL,
	"idempotency_key" text NOT NULL,
	"state" text NOT NULL,
	"attempt_count" integer DEFAULT 0 NOT NULL,
	"next_attempt_at" timestamp with time zone NOT NULL,
	"provider_message_id" text,
	"last_error_code" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"sent_at" timestamp with time zone,
	CONSTRAINT "email_outbox_idempotency_key_unique" UNIQUE("idempotency_key"),
	CONSTRAINT "email_outbox_state_valid" CHECK ("private"."email_outbox"."state" in ('pending', 'sending', 'sent', 'failed_retryable', 'dead_letter')),
	CONSTRAINT "email_outbox_attempt_count_nonnegative" CHECK ("private"."email_outbox"."attempt_count" >= 0)
);
--> statement-breakpoint
CREATE TABLE "private"."financial_ledger" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"listing_id" uuid NOT NULL,
	"entry_type" text NOT NULL,
	"amount_delta_paise" bigint NOT NULL,
	"currency" text NOT NULL,
	"payment_attempt_id" uuid,
	"provider_payment_id" text,
	"provider_adjustment_id" text,
	"reverses_ledger_entry_id" uuid,
	"policy_version" text NOT NULL,
	"applied_at" timestamp with time zone NOT NULL,
	"applied_business_date" date NOT NULL,
	"provider_effective_at" timestamp with time zone,
	"created_by_admin_user_id" uuid,
	"reason_code" text,
	"source_key" text NOT NULL,
	"source_provider" text,
	"source_environment" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "financial_ledger_source_key_unique" UNIQUE("source_key"),
	CONSTRAINT "financial_ledger_entry_type_valid" CHECK ("private"."financial_ledger"."entry_type" in ('initial_sponsorship', 'raise', 'refund', 'chargeback', 'refund_restoration', 'chargeback_restoration', 'admin_financial_correction')),
	CONSTRAINT "financial_ledger_amount_valid" CHECK ("private"."financial_ledger"."amount_delta_paise" <> 0 and "private"."financial_ledger"."amount_delta_paise" % 100 = 0),
	CONSTRAINT "financial_ledger_currency_inr" CHECK ("private"."financial_ledger"."currency" = 'INR'),
	CONSTRAINT "financial_ledger_entry_sign_valid" CHECK (("private"."financial_ledger"."entry_type" in ('initial_sponsorship', 'raise', 'refund_restoration', 'chargeback_restoration') and "private"."financial_ledger"."amount_delta_paise" > 0) or ("private"."financial_ledger"."entry_type" in ('refund', 'chargeback') and "private"."financial_ledger"."amount_delta_paise" < 0) or "private"."financial_ledger"."entry_type" = 'admin_financial_correction'),
	CONSTRAINT "financial_ledger_fulfilment_attempt_required" CHECK ("private"."financial_ledger"."entry_type" not in ('initial_sponsorship', 'raise') or "private"."financial_ledger"."payment_attempt_id" is not null),
	CONSTRAINT "financial_ledger_business_date_valid" CHECK ("private"."financial_ledger"."applied_business_date" = ("private"."financial_ledger"."applied_at" at time zone 'Asia/Kolkata')::date)
);
--> statement-breakpoint
CREATE TABLE "private"."listing_change_requests" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"listing_id" uuid NOT NULL,
	"requested_by_user_id" uuid NOT NULL,
	"change_type" text NOT NULL,
	"old_value" jsonb NOT NULL,
	"proposed_value" jsonb NOT NULL,
	"state" text NOT NULL,
	"reviewed_by_admin_id" uuid,
	"review_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"reviewed_at" timestamp with time zone,
	CONSTRAINT "listing_change_requests_state_valid" CHECK ("private"."listing_change_requests"."state" in ('pending', 'approved', 'rejected', 'cancelled'))
);
--> statement-breakpoint
CREATE TABLE "private"."listing_owners" (
	"listing_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"role" text DEFAULT 'owner' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp with time zone,
	"created_by" uuid,
	CONSTRAINT "listing_owners_listing_id_user_id_pk" PRIMARY KEY("listing_id","user_id"),
	CONSTRAINT "listing_owners_role_valid" CHECK ("private"."listing_owners"."role" = 'owner')
);
--> statement-breakpoint
CREATE TABLE "private"."listing_screenings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"listing_id" uuid NOT NULL,
	"screening_version" text NOT NULL,
	"result" text NOT NULL,
	"result_codes" jsonb NOT NULL,
	"request_fingerprint" text,
	"screened_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "listing_screenings_result_valid" CHECK ("private"."listing_screenings"."result" in ('clear', 'pending_review', 'rejected'))
);
--> statement-breakpoint
CREATE TABLE "private"."moderation_actions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"listing_id" uuid NOT NULL,
	"action_type" text NOT NULL,
	"from_status" text,
	"to_status" text,
	"reason_code" text NOT NULL,
	"public_reason" text,
	"internal_note" text,
	"admin_user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "private"."operational_flags" (
	"key" text PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"updated_by" uuid,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "private"."payment_attempts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"public_id" text NOT NULL,
	"application_idempotency_key" text NOT NULL,
	"provider" text NOT NULL,
	"provider_environment" text NOT NULL,
	"provider_order_id" text,
	"provider_checkout_session_id" text,
	"listing_id" uuid NOT NULL,
	"purpose" text NOT NULL,
	"state" text NOT NULL,
	"amount_paise" bigint NOT NULL,
	"currency" text DEFAULT 'INR' NOT NULL,
	"policy_version" text NOT NULL,
	"minimum_required_paise_snapshot" bigint NOT NULL,
	"target_listing_id_snapshot" uuid,
	"target_rank_snapshot" integer,
	"target_total_paise_snapshot" bigint,
	"listing_total_paise_snapshot" bigint NOT NULL,
	"estimated_rank_snapshot" integer,
	"requested_by_user_id" uuid,
	"pending_owner_id" uuid,
	"provider_order_request_hash" text NOT NULL,
	"checkout_expires_at" timestamp with time zone NOT NULL,
	"fulfilled_ledger_entry_id" uuid,
	"failure_code" text,
	"quarantine_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"provider_created_at" timestamp with time zone,
	"succeeded_at" timestamp with time zone,
	"expired_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "payment_attempts_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "payment_attempts_environment_idempotency_unique" UNIQUE("provider_environment","application_idempotency_key"),
	CONSTRAINT "payment_attempts_purpose_valid" CHECK ("private"."payment_attempts"."purpose" in ('initial_sponsorship', 'raise')),
	CONSTRAINT "payment_attempts_state_valid" CHECK ("private"."payment_attempts"."state" in ('intent_created', 'provider_order_pending', 'checkout_ready', 'customer_returned', 'provider_pending', 'succeeded', 'failed', 'dropped', 'expired', 'quarantined', 'duplicate_paid', 'cancelled')),
	CONSTRAINT "payment_attempts_amount_valid" CHECK ("private"."payment_attempts"."amount_paise" > 0 and "private"."payment_attempts"."amount_paise" % 100 = 0),
	CONSTRAINT "payment_attempts_currency_inr" CHECK ("private"."payment_attempts"."currency" = 'INR'),
	CONSTRAINT "payment_attempts_minimum_valid" CHECK ("private"."payment_attempts"."minimum_required_paise_snapshot" > 0 and "private"."payment_attempts"."minimum_required_paise_snapshot" % 100 = 0 and "private"."payment_attempts"."amount_paise" >= "private"."payment_attempts"."minimum_required_paise_snapshot"),
	CONSTRAINT "payment_attempts_listing_snapshot_valid" CHECK ("private"."payment_attempts"."listing_total_paise_snapshot" >= 0 and "private"."payment_attempts"."listing_total_paise_snapshot" % 100 = 0),
	CONSTRAINT "payment_attempts_target_snapshot_valid" CHECK (("private"."payment_attempts"."target_total_paise_snapshot" is null or ("private"."payment_attempts"."target_total_paise_snapshot" >= 0 and "private"."payment_attempts"."target_total_paise_snapshot" % 100 = 0)) and ("private"."payment_attempts"."target_rank_snapshot" is null or "private"."payment_attempts"."target_rank_snapshot" > 0) and ("private"."payment_attempts"."estimated_rank_snapshot" is null or "private"."payment_attempts"."estimated_rank_snapshot" > 0)),
	CONSTRAINT "payment_attempts_actor_valid" CHECK (("private"."payment_attempts"."purpose" = 'initial_sponsorship' and "private"."payment_attempts"."pending_owner_id" is not null) or ("private"."payment_attempts"."purpose" = 'raise' and "private"."payment_attempts"."requested_by_user_id" is not null and "private"."payment_attempts"."pending_owner_id" is null)),
	CONSTRAINT "payment_attempts_checkout_expiry_valid" CHECK ("private"."payment_attempts"."checkout_expires_at" > "private"."payment_attempts"."created_at"),
	CONSTRAINT "payment_attempts_fulfilment_state_valid" CHECK ("private"."payment_attempts"."state" <> 'succeeded' or ("private"."payment_attempts"."fulfilled_ledger_entry_id" is not null and "private"."payment_attempts"."succeeded_at" is not null))
);
--> statement-breakpoint
CREATE TABLE "private"."pending_listing_owners" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"listing_id" uuid NOT NULL,
	"canonical_email" text NOT NULL,
	"encrypted_email" text,
	"email_hash" text NOT NULL,
	"claim_state" text NOT NULL,
	"created_from_attempt_id" uuid,
	"claimed_by_user_id" uuid,
	"claimed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "pending_listing_owners_listing_unique" UNIQUE("listing_id"),
	CONSTRAINT "pending_listing_owners_claim_state_valid" CHECK ("private"."pending_listing_owners"."claim_state" in ('pending', 'claimed', 'superseded')),
	CONSTRAINT "pending_listing_owners_claim_fields_valid" CHECK ("private"."pending_listing_owners"."claim_state" <> 'claimed' or ("private"."pending_listing_owners"."claimed_by_user_id" is not null and "private"."pending_listing_owners"."claimed_at" is not null))
);
--> statement-breakpoint
CREATE TABLE "private"."provider_adjustments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"provider" text NOT NULL,
	"provider_environment" text NOT NULL,
	"provider_adjustment_id" text NOT NULL,
	"provider_payment_id" text NOT NULL,
	"payment_attempt_id" uuid,
	"listing_id" uuid,
	"kind" text NOT NULL,
	"status" text NOT NULL,
	"amount_paise" bigint NOT NULL,
	"currency" text NOT NULL,
	"desired_effective_delta" bigint NOT NULL,
	"currently_applied_delta" bigint DEFAULT 0 NOT NULL,
	"applies_to_ledger_entry_id" uuid,
	"rank_effect_eligible" boolean DEFAULT false NOT NULL,
	"provider_created_at" timestamp with time zone,
	"provider_updated_at" timestamp with time zone,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "provider_adjustments_identity_unique" UNIQUE("provider","provider_environment","provider_adjustment_id"),
	CONSTRAINT "provider_adjustments_kind_valid" CHECK ("private"."provider_adjustments"."kind" in ('refund', 'chargeback', 'reversal', 'correction')),
	CONSTRAINT "provider_adjustments_amount_valid" CHECK ("private"."provider_adjustments"."amount_paise" > 0 and "private"."provider_adjustments"."amount_paise" % 100 = 0),
	CONSTRAINT "provider_adjustments_delta_valid" CHECK ("private"."provider_adjustments"."desired_effective_delta" in (0, -"private"."provider_adjustments"."amount_paise") and "private"."provider_adjustments"."currently_applied_delta" <= 0 and "private"."provider_adjustments"."currently_applied_delta" >= -"private"."provider_adjustments"."amount_paise" and "private"."provider_adjustments"."currently_applied_delta" % 100 = 0),
	CONSTRAINT "provider_adjustments_currency_valid" CHECK (char_length("private"."provider_adjustments"."currency") = 3)
);
--> statement-breakpoint
CREATE TABLE "private"."provider_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"provider" text NOT NULL,
	"provider_environment" text NOT NULL,
	"provider_event_id" text NOT NULL,
	"provider_event_type" text NOT NULL,
	"signature_status" text NOT NULL,
	"raw_body_digest" text NOT NULL,
	"raw_payload_encrypted" text,
	"provider_created_at" timestamp with time zone,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL,
	"processing_state" text NOT NULL,
	"normalized_event_type" text,
	"payment_attempt_id" uuid,
	"provider_payment_id" text,
	"semantic_error_code" text,
	"processed_at" timestamp with time zone,
	"last_error_code" text,
	"attempt_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "provider_events_identity_unique" UNIQUE("provider","provider_environment","provider_event_id"),
	CONSTRAINT "provider_events_signature_status_valid" CHECK ("private"."provider_events"."signature_status" in ('verified', 'invalid', 'not_checked')),
	CONSTRAINT "provider_events_processing_state_valid" CHECK ("private"."provider_events"."processing_state" in ('received', 'processing', 'processed', 'quarantined', 'failed_retryable')),
	CONSTRAINT "provider_events_attempt_count_nonnegative" CHECK ("private"."provider_events"."attempt_count" >= 0)
);
--> statement-breakpoint
CREATE TABLE "private"."provider_payments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"provider" text NOT NULL,
	"provider_environment" text NOT NULL,
	"provider_payment_id" text NOT NULL,
	"provider_order_id" text NOT NULL,
	"payment_attempt_id" uuid,
	"amount_paise" bigint NOT NULL,
	"currency" text NOT NULL,
	"status" text NOT NULL,
	"payment_method_family" text,
	"provider_created_at" timestamp with time zone,
	"provider_updated_at" timestamp with time zone,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"settled_at" timestamp with time zone,
	"fulfilled_ledger_entry_id" uuid,
	"raw_snapshot_encrypted" text,
	CONSTRAINT "provider_payments_identity_unique" UNIQUE("provider","provider_environment","provider_payment_id"),
	CONSTRAINT "provider_payments_amount_valid" CHECK ("private"."provider_payments"."amount_paise" > 0 and "private"."provider_payments"."amount_paise" % 100 = 0),
	CONSTRAINT "provider_payments_currency_valid" CHECK (char_length("private"."provider_payments"."currency") = 3)
);
--> statement-breakpoint
CREATE TABLE "private"."rate_limit_buckets" (
	"scope" text NOT NULL,
	"subject_hmac" text NOT NULL,
	"window_start" timestamp with time zone NOT NULL,
	"count" bigint DEFAULT 0 NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	CONSTRAINT "rate_limit_buckets_scope_subject_hmac_window_start_pk" PRIMARY KEY("scope","subject_hmac","window_start"),
	CONSTRAINT "rate_limit_buckets_count_positive" CHECK ("private"."rate_limit_buckets"."count" > 0),
	CONSTRAINT "rate_limit_buckets_expiry_valid" CHECK ("private"."rate_limit_buckets"."expires_at" > "private"."rate_limit_buckets"."window_start")
);
--> statement-breakpoint
CREATE TABLE "private"."reconciliation_items" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"run_id" uuid NOT NULL,
	"provider_object_type" text NOT NULL,
	"provider_object_id" text NOT NULL,
	"payment_attempt_id" uuid,
	"listing_id" uuid,
	"discrepancy_type" text NOT NULL,
	"expected" jsonb,
	"actual" jsonb,
	"state" text NOT NULL,
	"resolution" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"resolved_at" timestamp with time zone,
	"resolved_by" uuid,
	CONSTRAINT "reconciliation_items_run_object_discrepancy_unique" UNIQUE("run_id","provider_object_type","provider_object_id","discrepancy_type"),
	CONSTRAINT "reconciliation_items_state_valid" CHECK ("private"."reconciliation_items"."state" in ('open', 'investigating', 'resolved', 'ignored'))
);
--> statement-breakpoint
CREATE TABLE "private"."reconciliation_runs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"provider" text NOT NULL,
	"environment" text NOT NULL,
	"kind" text NOT NULL,
	"window_start" timestamp with time zone NOT NULL,
	"window_end" timestamp with time zone NOT NULL,
	"state" text NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"counts" jsonb NOT NULL,
	"error_summary" text,
	CONSTRAINT "reconciliation_runs_window_valid" CHECK ("private"."reconciliation_runs"."window_end" >= "private"."reconciliation_runs"."window_start"),
	CONSTRAINT "reconciliation_runs_state_valid" CHECK ("private"."reconciliation_runs"."state" in ('running', 'completed', 'failed'))
);
--> statement-breakpoint
CREATE TABLE "private"."reports" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"public_id" text NOT NULL,
	"listing_id" uuid NOT NULL,
	"reason_category" text NOT NULL,
	"explanation" text NOT NULL,
	"reporter_email_encrypted" text,
	"reporter_email_hash" text,
	"request_fingerprint" text NOT NULL,
	"state" text NOT NULL,
	"turnstile_result" text,
	"reviewed_by_admin_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"reviewed_at" timestamp with time zone,
	CONSTRAINT "reports_public_id_unique" UNIQUE("public_id"),
	CONSTRAINT "reports_reason_category_valid" CHECK ("private"."reports"."reason_category" in ('harmful_illegal', 'impersonation', 'scam', 'malware_phishing', 'adult', 'ip_counterfeit', 'other')),
	CONSTRAINT "reports_state_valid" CHECK ("private"."reports"."state" in ('pending', 'reviewing', 'resolved', 'dismissed'))
);
--> statement-breakpoint
ALTER TABLE "app"."listing_assets" ADD CONSTRAINT "listing_assets_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "app"."listings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."listing_click_daily_totals" ADD CONSTRAINT "listing_click_daily_totals_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "app"."listings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."listing_daily_totals" ADD CONSTRAINT "listing_daily_totals_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "app"."listings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."listings" ADD CONSTRAINT "listings_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "app"."categories"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."click_dedupe" ADD CONSTRAINT "click_dedupe_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "app"."listings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."financial_ledger" ADD CONSTRAINT "financial_ledger_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "app"."listings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."financial_ledger" ADD CONSTRAINT "financial_ledger_payment_attempt_id_payment_attempts_id_fk" FOREIGN KEY ("payment_attempt_id") REFERENCES "private"."payment_attempts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."listing_change_requests" ADD CONSTRAINT "listing_change_requests_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "app"."listings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."listing_owners" ADD CONSTRAINT "listing_owners_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "app"."listings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."listing_screenings" ADD CONSTRAINT "listing_screenings_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "app"."listings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."moderation_actions" ADD CONSTRAINT "moderation_actions_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "app"."listings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."payment_attempts" ADD CONSTRAINT "payment_attempts_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "app"."listings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."payment_attempts" ADD CONSTRAINT "payment_attempts_target_listing_id_snapshot_listings_id_fk" FOREIGN KEY ("target_listing_id_snapshot") REFERENCES "app"."listings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."payment_attempts" ADD CONSTRAINT "payment_attempts_pending_owner_id_pending_listing_owners_id_fk" FOREIGN KEY ("pending_owner_id") REFERENCES "private"."pending_listing_owners"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."pending_listing_owners" ADD CONSTRAINT "pending_listing_owners_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "app"."listings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."provider_adjustments" ADD CONSTRAINT "provider_adjustments_payment_attempt_id_payment_attempts_id_fk" FOREIGN KEY ("payment_attempt_id") REFERENCES "private"."payment_attempts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."provider_adjustments" ADD CONSTRAINT "provider_adjustments_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "app"."listings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."provider_events" ADD CONSTRAINT "provider_events_payment_attempt_id_payment_attempts_id_fk" FOREIGN KEY ("payment_attempt_id") REFERENCES "private"."payment_attempts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."provider_payments" ADD CONSTRAINT "provider_payments_payment_attempt_id_payment_attempts_id_fk" FOREIGN KEY ("payment_attempt_id") REFERENCES "private"."payment_attempts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."reconciliation_items" ADD CONSTRAINT "reconciliation_items_run_id_reconciliation_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "private"."reconciliation_runs"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."reconciliation_items" ADD CONSTRAINT "reconciliation_items_payment_attempt_id_payment_attempts_id_fk" FOREIGN KEY ("payment_attempt_id") REFERENCES "private"."payment_attempts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."reconciliation_items" ADD CONSTRAINT "reconciliation_items_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "app"."listings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "private"."reports" ADD CONSTRAINT "reports_listing_id_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "app"."listings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "listing_assets_staging_object_key_unique" ON "app"."listing_assets" USING btree ("staging_object_key") WHERE "app"."listing_assets"."staging_object_key" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "listing_assets_public_object_key_unique" ON "app"."listing_assets" USING btree ("public_object_key") WHERE "app"."listing_assets"."public_object_key" is not null;--> statement-breakpoint
CREATE INDEX "listing_assets_listing_created_idx" ON "app"."listing_assets" USING btree ("listing_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "listing_assets_expiry_idx" ON "app"."listing_assets" USING btree ("state","expires_at");--> statement-breakpoint
CREATE INDEX "listing_daily_totals_ranking_idx" ON "app"."listing_daily_totals" USING btree ("business_date","net_amount_paise" DESC NULLS LAST,"total_reached_at","listing_id");--> statement-breakpoint
CREATE INDEX "listings_main_ranking_idx" ON "app"."listings" USING btree ("lifecycle_status","moderation_status","confirmed_total_paise" DESC NULLS LAST,"current_total_reached_at","id");--> statement-breakpoint
CREATE INDEX "listings_category_ranking_idx" ON "app"."listings" USING btree ("category_id","lifecycle_status","moderation_status","confirmed_total_paise" DESC NULLS LAST,"current_total_reached_at","id");--> statement-breakpoint
CREATE INDEX "listings_destination_host_idx" ON "app"."listings" USING btree ("destination_host");--> statement-breakpoint
CREATE INDEX "listings_created_at_idx" ON "app"."listings" USING btree ("created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "admin_audit_events_target_created_idx" ON "private"."admin_audit_events" USING btree ("target_type","target_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "admin_audit_events_actor_created_idx" ON "private"."admin_audit_events" USING btree ("actor_user_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "click_dedupe_expiry_idx" ON "private"."click_dedupe" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "email_outbox_delivery_idx" ON "private"."email_outbox" USING btree ("state","next_attempt_at");--> statement-breakpoint
CREATE UNIQUE INDEX "financial_ledger_positive_fulfilment_unique" ON "private"."financial_ledger" USING btree ("payment_attempt_id") WHERE "private"."financial_ledger"."entry_type" in ('initial_sponsorship', 'raise');--> statement-breakpoint
CREATE INDEX "financial_ledger_listing_applied_idx" ON "private"."financial_ledger" USING btree ("listing_id","applied_at","id");--> statement-breakpoint
CREATE INDEX "financial_ledger_listing_business_date_idx" ON "private"."financial_ledger" USING btree ("listing_id","applied_business_date");--> statement-breakpoint
CREATE INDEX "financial_ledger_payment_attempt_idx" ON "private"."financial_ledger" USING btree ("payment_attempt_id");--> statement-breakpoint
CREATE INDEX "financial_ledger_provider_payment_idx" ON "private"."financial_ledger" USING btree ("provider_payment_id");--> statement-breakpoint
CREATE INDEX "financial_ledger_provider_adjustment_idx" ON "private"."financial_ledger" USING btree ("provider_adjustment_id");--> statement-breakpoint
CREATE INDEX "financial_ledger_business_applied_idx" ON "private"."financial_ledger" USING btree ("applied_business_date","applied_at");--> statement-breakpoint
CREATE UNIQUE INDEX "listing_change_requests_one_pending_type" ON "private"."listing_change_requests" USING btree ("listing_id","change_type") WHERE "private"."listing_change_requests"."state" = 'pending';--> statement-breakpoint
CREATE INDEX "listing_change_requests_state_created_idx" ON "private"."listing_change_requests" USING btree ("state","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "listing_owners_one_active_owner_per_listing" ON "private"."listing_owners" USING btree ("listing_id") WHERE "private"."listing_owners"."revoked_at" is null;--> statement-breakpoint
CREATE INDEX "listing_owners_active_user_idx" ON "private"."listing_owners" USING btree ("user_id","listing_id") WHERE "private"."listing_owners"."revoked_at" is null;--> statement-breakpoint
CREATE INDEX "listing_screenings_listing_screened_idx" ON "private"."listing_screenings" USING btree ("listing_id","screened_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "moderation_actions_listing_created_idx" ON "private"."moderation_actions" USING btree ("listing_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "payment_attempts_provider_order_unique" ON "private"."payment_attempts" USING btree ("provider","provider_environment","provider_order_id") WHERE "private"."payment_attempts"."provider_order_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "payment_attempts_fulfilled_ledger_unique" ON "private"."payment_attempts" USING btree ("fulfilled_ledger_entry_id") WHERE "private"."payment_attempts"."fulfilled_ledger_entry_id" is not null;--> statement-breakpoint
CREATE INDEX "payment_attempts_listing_created_idx" ON "private"."payment_attempts" USING btree ("listing_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "payment_attempts_state_created_idx" ON "private"."payment_attempts" USING btree ("state","created_at");--> statement-breakpoint
CREATE INDEX "payment_attempts_provider_order_idx" ON "private"."payment_attempts" USING btree ("provider","provider_environment","provider_order_id");--> statement-breakpoint
CREATE INDEX "payment_attempts_requester_created_idx" ON "private"."payment_attempts" USING btree ("requested_by_user_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "payment_attempts_checkout_expiry_idx" ON "private"."payment_attempts" USING btree ("checkout_expires_at") WHERE "private"."payment_attempts"."state" in ('intent_created', 'provider_order_pending', 'checkout_ready', 'customer_returned', 'provider_pending');--> statement-breakpoint
CREATE INDEX "pending_listing_owners_email_hash_idx" ON "private"."pending_listing_owners" USING btree ("email_hash");--> statement-breakpoint
CREATE INDEX "provider_adjustments_payment_idx" ON "private"."provider_adjustments" USING btree ("provider","provider_environment","provider_payment_id");--> statement-breakpoint
CREATE INDEX "provider_adjustments_attempt_idx" ON "private"."provider_adjustments" USING btree ("payment_attempt_id");--> statement-breakpoint
CREATE INDEX "provider_events_attempt_received_idx" ON "private"."provider_events" USING btree ("payment_attempt_id","received_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "provider_events_processing_received_idx" ON "private"."provider_events" USING btree ("processing_state","received_at");--> statement-breakpoint
CREATE UNIQUE INDEX "provider_payments_fulfilled_ledger_unique" ON "private"."provider_payments" USING btree ("fulfilled_ledger_entry_id") WHERE "private"."provider_payments"."fulfilled_ledger_entry_id" is not null;--> statement-breakpoint
CREATE INDEX "provider_payments_order_idx" ON "private"."provider_payments" USING btree ("provider","provider_environment","provider_order_id");--> statement-breakpoint
CREATE INDEX "provider_payments_attempt_idx" ON "private"."provider_payments" USING btree ("payment_attempt_id");--> statement-breakpoint
CREATE INDEX "rate_limit_buckets_expiry_idx" ON "private"."rate_limit_buckets" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "reconciliation_items_state_created_idx" ON "private"."reconciliation_items" USING btree ("state","created_at");--> statement-breakpoint
CREATE INDEX "reconciliation_items_attempt_idx" ON "private"."reconciliation_items" USING btree ("payment_attempt_id");--> statement-breakpoint
CREATE INDEX "reconciliation_items_listing_idx" ON "private"."reconciliation_items" USING btree ("listing_id");--> statement-breakpoint
CREATE INDEX "reconciliation_runs_provider_started_idx" ON "private"."reconciliation_runs" USING btree ("provider","environment","started_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "reports_listing_created_idx" ON "private"."reports" USING btree ("listing_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "reports_state_created_idx" ON "private"."reports" USING btree ("state","created_at");

-- Drizzle intentionally leaves platform-managed auth and circular references
-- for explicit review here.
ALTER TABLE "app"."listings"
  ADD CONSTRAINT "listings_logo_asset_id_listing_assets_id_fk"
  FOREIGN KEY ("logo_asset_id") REFERENCES "app"."listing_assets"("id")
  ON DELETE RESTRICT;

ALTER TABLE "app"."listing_daily_totals"
  ADD CONSTRAINT "listing_daily_last_ledger_fk"
  FOREIGN KEY ("last_ledger_entry_id") REFERENCES "private"."financial_ledger"("id")
  ON DELETE RESTRICT;

ALTER TABLE "private"."pending_listing_owners"
  ADD CONSTRAINT "pending_owner_created_attempt_fk"
  FOREIGN KEY ("created_from_attempt_id") REFERENCES "private"."payment_attempts"("id")
  ON DELETE RESTRICT,
  ADD CONSTRAINT "pending_listing_owners_claimed_by_user_id_auth_users_id_fk"
  FOREIGN KEY ("claimed_by_user_id") REFERENCES "auth"."users"("id")
  ON DELETE RESTRICT;

ALTER TABLE "private"."listing_owners"
  ADD CONSTRAINT "listing_owners_user_id_auth_users_id_fk"
  FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id")
  ON DELETE RESTRICT,
  ADD CONSTRAINT "listing_owners_created_by_auth_users_id_fk"
  FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id")
  ON DELETE RESTRICT;

ALTER TABLE "private"."payment_attempts"
  ADD CONSTRAINT "payment_attempts_requested_by_user_id_auth_users_id_fk"
  FOREIGN KEY ("requested_by_user_id") REFERENCES "auth"."users"("id")
  ON DELETE RESTRICT,
  ADD CONSTRAINT "payment_attempt_fulfilled_ledger_fk"
  FOREIGN KEY ("fulfilled_ledger_entry_id") REFERENCES "private"."financial_ledger"("id")
  ON DELETE RESTRICT;

ALTER TABLE "private"."provider_payments"
  ADD CONSTRAINT "provider_payment_fulfilled_ledger_fk"
  FOREIGN KEY ("fulfilled_ledger_entry_id") REFERENCES "private"."financial_ledger"("id")
  ON DELETE RESTRICT;

ALTER TABLE "private"."provider_adjustments"
  ADD CONSTRAINT "provider_adjustments_payment_identity_fk"
  FOREIGN KEY ("provider", "provider_environment", "provider_payment_id")
  REFERENCES "private"."provider_payments"("provider", "provider_environment", "provider_payment_id")
  ON DELETE RESTRICT,
  ADD CONSTRAINT "provider_adjustment_applies_ledger_fk"
  FOREIGN KEY ("applies_to_ledger_entry_id") REFERENCES "private"."financial_ledger"("id")
  ON DELETE RESTRICT;

ALTER TABLE "private"."financial_ledger"
  ADD CONSTRAINT "ledger_reverses_ledger_fk"
  FOREIGN KEY ("reverses_ledger_entry_id") REFERENCES "private"."financial_ledger"("id")
  ON DELETE RESTRICT,
  ADD CONSTRAINT "financial_ledger_created_by_admin_user_id_auth_users_id_fk"
  FOREIGN KEY ("created_by_admin_user_id") REFERENCES "auth"."users"("id")
  ON DELETE RESTRICT;

ALTER TABLE "private"."listing_change_requests"
  ADD CONSTRAINT "listing_change_requests_requested_by_user_id_auth_users_id_fk"
  FOREIGN KEY ("requested_by_user_id") REFERENCES "auth"."users"("id")
  ON DELETE RESTRICT,
  ADD CONSTRAINT "listing_change_requests_reviewed_by_admin_id_auth_users_id_fk"
  FOREIGN KEY ("reviewed_by_admin_id") REFERENCES "auth"."users"("id")
  ON DELETE RESTRICT;

ALTER TABLE "private"."reports"
  ADD CONSTRAINT "reports_reviewed_by_admin_id_auth_users_id_fk"
  FOREIGN KEY ("reviewed_by_admin_id") REFERENCES "auth"."users"("id")
  ON DELETE RESTRICT;

ALTER TABLE "private"."admin_users"
  ADD CONSTRAINT "admin_users_user_id_auth_users_id_fk"
  FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id")
  ON DELETE RESTRICT,
  ADD CONSTRAINT "admin_users_created_by_auth_users_id_fk"
  FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id")
  ON DELETE RESTRICT;

ALTER TABLE "private"."moderation_actions"
  ADD CONSTRAINT "moderation_actions_admin_user_id_auth_users_id_fk"
  FOREIGN KEY ("admin_user_id") REFERENCES "auth"."users"("id")
  ON DELETE RESTRICT;

ALTER TABLE "private"."admin_audit_events"
  ADD CONSTRAINT "admin_audit_events_actor_user_id_auth_users_id_fk"
  FOREIGN KEY ("actor_user_id") REFERENCES "auth"."users"("id")
  ON DELETE RESTRICT;

ALTER TABLE "private"."operational_flags"
  ADD CONSTRAINT "operational_flags_updated_by_auth_users_id_fk"
  FOREIGN KEY ("updated_by") REFERENCES "auth"."users"("id")
  ON DELETE RESTRICT;

ALTER TABLE "private"."reconciliation_items"
  ADD CONSTRAINT "reconciliation_items_resolved_by_auth_users_id_fk"
  FOREIGN KEY ("resolved_by") REFERENCES "auth"."users"("id")
  ON DELETE RESTRICT;

-- Canonical category reference data. Stable IDs make fixtures and deployments
-- reproducible; the upsert is idempotent without silently creating extras.
INSERT INTO "app"."categories" (
  "id", "slug", "name", "sort_order", "is_active"
)
VALUES
  ('00000000-0000-4000-8000-000000000001', 'people-creators', 'People & Creators', 1, true),
  ('00000000-0000-4000-8000-000000000002', 'tech-apps', 'Tech & Apps', 2, true),
  ('00000000-0000-4000-8000-000000000003', 'brands-d2c', 'Brands & D2C', 3, true),
  ('00000000-0000-4000-8000-000000000004', 'b2b-services', 'B2B & Services', 4, true),
  ('00000000-0000-4000-8000-000000000005', 'media-entertainment', 'Media & Entertainment', 5, true),
  ('00000000-0000-4000-8000-000000000006', 'other', 'Other', 6, true)
ON CONFLICT ("id") DO UPDATE SET
  "slug" = EXCLUDED."slug",
  "name" = EXCLUDED."name",
  "sort_order" = EXCLUDED."sort_order",
  "is_active" = EXCLUDED."is_active",
  "updated_at" = CASE
    WHEN (
      "categories"."slug",
      "categories"."name",
      "categories"."sort_order",
      "categories"."is_active"
    ) IS DISTINCT FROM (
      EXCLUDED."slug",
      EXCLUDED."name",
      EXCLUDED."sort_order",
      EXCLUDED."is_active"
    ) THEN transaction_timestamp()
    ELSE "categories"."updated_at"
  END;

-- Simple last-line immutability protections. These are SECURITY INVOKER (the
-- default), have a fixed search_path and are not callable as a public API.
CREATE FUNCTION "private"."reject_append_only_mutation"()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $$
BEGIN
  RAISE EXCEPTION '% is append-only; % is forbidden', TG_TABLE_SCHEMA || '.' || TG_TABLE_NAME, TG_OP
    USING ERRCODE = '55000';
END;
$$;

REVOKE ALL ON FUNCTION "private"."reject_append_only_mutation"() FROM PUBLIC;

CREATE TRIGGER "financial_ledger_append_only"
BEFORE UPDATE OR DELETE ON "private"."financial_ledger"
FOR EACH ROW EXECUTE FUNCTION "private"."reject_append_only_mutation"();

CREATE TRIGGER "moderation_actions_append_only"
BEFORE UPDATE OR DELETE ON "private"."moderation_actions"
FOR EACH ROW EXECUTE FUNCTION "private"."reject_append_only_mutation"();

CREATE TRIGGER "admin_audit_events_append_only"
BEFORE UPDATE OR DELETE ON "private"."admin_audit_events"
FOR EACH ROW EXECUTE FUNCTION "private"."reject_append_only_mutation"();

CREATE TRIGGER "listing_screenings_append_only"
BEFORE UPDATE OR DELETE ON "private"."listing_screenings"
FOR EACH ROW EXECUTE FUNCTION "private"."reject_append_only_mutation"();

CREATE FUNCTION "private"."protect_listing_original_sponsorship"()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $$
BEGIN
  IF OLD.original_sponsorship_paise IS NOT NULL
     AND NEW.original_sponsorship_paise IS DISTINCT FROM OLD.original_sponsorship_paise THEN
    RAISE EXCEPTION 'original_sponsorship_paise is immutable after first confirmation'
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION "private"."protect_listing_original_sponsorship"() FROM PUBLIC;

CREATE TRIGGER "listings_original_sponsorship_immutable"
BEFORE UPDATE ON "app"."listings"
FOR EACH ROW EXECUTE FUNCTION "private"."protect_listing_original_sponsorship"();

CREATE FUNCTION "private"."protect_payment_attempt_intent"()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $$
BEGIN
  IF (
    NEW.id,
    NEW.public_id,
    NEW.application_idempotency_key,
    NEW.provider,
    NEW.provider_environment,
    NEW.listing_id,
    NEW.purpose,
    NEW.amount_paise,
    NEW.currency,
    NEW.policy_version,
    NEW.minimum_required_paise_snapshot,
    NEW.target_listing_id_snapshot,
    NEW.target_rank_snapshot,
    NEW.target_total_paise_snapshot,
    NEW.listing_total_paise_snapshot,
    NEW.estimated_rank_snapshot,
    NEW.requested_by_user_id,
    NEW.pending_owner_id,
    NEW.provider_order_request_hash,
    NEW.checkout_expires_at,
    NEW.created_at
  ) IS DISTINCT FROM (
    OLD.id,
    OLD.public_id,
    OLD.application_idempotency_key,
    OLD.provider,
    OLD.provider_environment,
    OLD.listing_id,
    OLD.purpose,
    OLD.amount_paise,
    OLD.currency,
    OLD.policy_version,
    OLD.minimum_required_paise_snapshot,
    OLD.target_listing_id_snapshot,
    OLD.target_rank_snapshot,
    OLD.target_total_paise_snapshot,
    OLD.listing_total_paise_snapshot,
    OLD.estimated_rank_snapshot,
    OLD.requested_by_user_id,
    OLD.pending_owner_id,
    OLD.provider_order_request_hash,
    OLD.checkout_expires_at,
    OLD.created_at
  ) THEN
    RAISE EXCEPTION 'payment attempt intent fields are immutable'
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION "private"."protect_payment_attempt_intent"() FROM PUBLIC;

CREATE TRIGGER "payment_attempts_intent_immutable"
BEFORE UPDATE ON "private"."payment_attempts"
FOR EACH ROW EXECUTE FUNCTION "private"."protect_payment_attempt_intent"();

-- Dedicated least-privilege group role for the server runtime. Environment-
-- specific login roles inherit this group; credentials are never migrated.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'goneviral_app') THEN
    CREATE ROLE goneviral_app NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
END;
$$;

GRANT goneviral_app TO postgres;

REVOKE ALL ON SCHEMA "app", "private" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON ALL TABLES IN SCHEMA "app", "private" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA "app", "private" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA "app", "private" FROM PUBLIC, anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA "app", "private"
  REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA "app", "private"
  REVOKE ALL ON SEQUENCES FROM PUBLIC, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA "app", "private"
  REVOKE ALL ON FUNCTIONS FROM PUBLIC, anon, authenticated, service_role;

GRANT USAGE ON SCHEMA "app", "private" TO goneviral_app;

GRANT SELECT ON "app"."categories" TO goneviral_app;
GRANT SELECT, INSERT, UPDATE ON
  "app"."listings",
  "app"."listing_assets",
  "app"."listing_daily_totals",
  "app"."listing_click_daily_totals"
TO goneviral_app;

GRANT SELECT, INSERT, UPDATE ON
  "private"."pending_listing_owners",
  "private"."listing_owners",
  "private"."payment_attempts",
  "private"."provider_events",
  "private"."provider_payments",
  "private"."provider_adjustments",
  "private"."listing_change_requests",
  "private"."reports",
  "private"."admin_users",
  "private"."email_outbox",
  "private"."operational_flags",
  "private"."reconciliation_runs",
  "private"."reconciliation_items"
TO goneviral_app;

GRANT SELECT, INSERT ON
  "private"."financial_ledger",
  "private"."moderation_actions",
  "private"."admin_audit_events",
  "private"."listing_screenings"
TO goneviral_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON
  "private"."click_dedupe",
  "private"."rate_limit_buckets"
TO goneviral_app;
